FROM node:20-slim

WORKDIR /app

# Copy dependency configuration
COPY package.json package-lock.json /app/

# Install node dependencies
RUN npm ci

# Copy React code
COPY . /app/

EXPOSE 5173

# Bind Vite to 0.0.0.0 so it is accessible from the host system
CMD ["npm", "run", "dev", "--", "--host"]
